# All tags
#     NOTE: Only when a post that has tags that are in `series`
#           AND whose category is "series", it will be represented in url("series")
tags:
- {series: false, name: 'Chinese',     tag: 'chinese',    description: '中文博客'}
- {series: false, name: 'English',     tag: 'english',    description: 'English Blog'}
- {series: false, name: 'Memory',      tag: 'memory',     description: '回忆与过去、那逝去的'}
- {series: false, name: 'AI',          tag: 'ai',         description: 'the outstanding AI'}
- {series: false, name: 'Diary',       tag: 'diary',      description: '记录性的、直抒胸臆的日志'}
- {series: true,  name: 'Trial',       tag: 'trial',      description: ''}
- {series: true,  name: 'Dostoevsky',  tag: 'dostoevsky', description: ''}

menu:
- {name: 'About',             url: 'about'}
- {name: 'Tags',              url: 'tags'}
- {name: 'Series',            url: 'series'}
- {name: 'Review',            url: 'review'}
- {name: 'Essay',             url: 'essay'}
- {name: 'Journal',           url: 'journal'}
- {name: 'Other',             url: 'other'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {family: 'brands', icon: 'github-alt',  link: 'https://github.com/huang-feiyu/huang-feiyu.github.io'}
- {family: 'solid',  icon: 'fish',        link: 'https://huang-feiyu.github.io/old'}
- {family: 'brands', icon: 'blogger-b',   link: 'https://huangfeiyu.blogspot.com'}
# - {icon: 'rss',          link: 'feed.xml'}

# Customize site text
pagination:
  next_page:     'Newer'
  previous_page: 'Older'

# See includes/post-share.html
# sharing_button_prompt: 'Feel free to share!'

# See includes/related-posts.html
# related_posts: 'You may also enjoy...'

post_date_prefix: 'Written <i>on</i>'

font_awesome_key: 'a945489fcb'

# For now, no 'comments' is supported
disqus:
  comments: false
  disqus_shortname: 'huangblog-1'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''
