# All tags
#     NOTE: Only when a post that has tags that are in `series`
#           AND whose category is "series", it will be represented in url("series")
tags:
- {series: false, name: 'Chinese',       tag: 'chinese',       description: '中文博客'}
- {series: false, name: 'English',       tag: 'english',       description: 'English Blog'}
- {series: false, name: 'Annual',        tag: 'annual',        description: '每年一度'}
- {series: false, name: 'Guide',         tag: 'guide',         description: '指导性、说明书类'}
- {series: false, name: 'Writing',       tag: 'writing',       description: '写作、刻意练习'}
- {series: false, name: 'Techonology',   tag: 'technology',    description: '科技领域'}
- {series: false, name: 'AI',            tag: 'ai',            description: 'the outstanding AI'}
- {series: false, name: 'Memory',        tag: 'memory',        description: '回忆与过去、那逝去的'}
- {series: false, name: 'School Life',   tag: 'school-life',   description: '大学四年的思想、生活经历'}
- {series: false, name: 'Kierkegaard',   tag: 'kierkegaard',   description: '索伦·克尔凯郭尔'}
- {series: true,  name: 'Dostoevsky',    tag: 'dostoevsky',    description: '费奥多尔·陀思妥耶夫斯基'}
- {series: false, name: 'Irrationalism', tag: 'irrationalism', description: '非理性、主观性'}

menu:
- {name: 'About',             url: 'about'}
- {name: 'Tags',              url: 'tags'}
- {name: 'Series',            url: 'series'}
- {name: 'Review',            url: 'review'}
- {name: 'Essay',             url: 'essay'}
- {name: 'Diary',             url: 'diary'}
- {name: 'Other',             url: 'other'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {family: 'brands', icon: 'github-alt',      link: 'https://github.com/huang-feiyu/huang-feiyu.github.io'}
- {family: 'solid',  icon: 'thumbs-up',       link: 'https://huang-feiyu.github.io/old'}
- {family: 'brands', icon: 'blogger-b',       link: 'https://huangfeiyu.blogspot.com'}
# - {family: 'solid',  icon: 'graduation-cap',  link: 'https://huang-feiyu.github.io/academics'}
# - {icon: 'rss',          link: 'feed.xml'}

# Customize site text
pagination:
  next_page:     'Newer'
  previous_page: 'Older'

# See includes/post-share.html
# sharing_button_prompt: 'Feel free to share!'

# See includes/related-posts.html
# related_posts: 'You may also enjoy...'

post_date_prefix: 'Written <i>on</i>'

font_awesome_key: 'a945489fcb'

# For now, no 'comments' is supported
disqus:
  comments: false
  disqus_shortname: 'huangblog-1'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''
